<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Bank;

class BankSeeder extends Seeder
{
    use WithoutModelEvents;
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Bank::upsert([
            ['code' => '001', 'name' => 'Banco do Brasil S.A.'],
            ['code' => '003', 'name' => 'Banco da Amazônia S.A.'],
            ['code' => '004', 'name' => 'Banco do Nordeste do Brasil S.A.'],
            ['code' => '007', 'name' => 'Banco Nacional de Desenvolvimento Econômico e Social'],
            ['code' => '012', 'name' => 'Banco Inbursa S.A.'],
            ['code' => '015', 'name' => 'Ubs Brasil S.A'],
            ['code' => '025', 'name' => 'Banco Alfa S.A.'],
            ['code' => '029', 'name' => 'Banco Itaú Consignado S.A.'],
            ['code' => '033', 'name' => 'Banco SANTANDER'],
            ['code' => '036', 'name' => 'Banco Bbi S.A'],
            ['code' => '037', 'name' => 'Banco do Estado do Pará S.A.'],
            ['code' => '040', 'name' => 'Banco Cargill S.A.'],
            ['code' => '041', 'name' => 'Banco do Estado do Rio Grande do Sul S.A.'],
            ['code' => '047', 'name' => 'Banco do Estado de Sergipe S.A.'],
            ['code' => '051', 'name' => 'Banco de Desenvolvimento do Espírito Santo S.A.'],
            ['code' => '062', 'name' => 'Hipercard Bm S.A'],
            ['code' => '063', 'name' => 'Banco Bradescard S.A.'],
            ['code' => '064', 'name' => 'Goldman Sachs Do Brasil Bm S.A'],
            ['code' => '065', 'name' => 'Banco Andbank (Brasil) S.A.'],
            ['code' => '066', 'name' => 'Banco Morgan Stanley S.A.'],
            ['code' => '069', 'name' => 'Banco Crefisa S.A.'],
            ['code' => '070', 'name' => 'BANCO DE BRASÍLIA (BRB)'],
            ['code' => '074', 'name' => 'Banco. J.Safra S.A'],
            ['code' => '075', 'name' => 'Banco ABN AMRO S.A'],
            ['code' => '076', 'name' => 'Banco KDB S.A.'],
            ['code' => '077', 'name' => 'Banco Inter S.A.'],
            ['code' => '079', 'name' => 'Banco Original Do Agronegócio S.A'],
            ['code' => '080', 'name' => 'B&T Cc Ltda'],
            ['code' => '082', 'name' => 'Banco Topázio S.A'],
            ['code' => '083', 'name' => 'Banco da China Brasil S.A.'],
            ['code' => '084', 'name' => 'Uniprime Norte Do Paraná'],
            ['code' => '085', 'name' => 'Coop Central Ailos'],
            ['code' => '091', 'name' => 'Unicred Central Rs'],
            ['code' => '093', 'name' => 'Pólocred Scmepp Ltda'],
            ['code' => '094', 'name' => 'Banco Finaxis S.A.'],
            ['code' => '096', 'name' => 'Banco B3 S.A.'],
            ['code' => '099', 'name' => 'Uniprime Central Ccc Ltda'],
            ['code' => '100', 'name' => 'Planner Corretora De Valores S.A'],
            ['code' => '102', 'name' => 'Xp Investimentos S.A'],
            ['code' => '104', 'name' => 'Banco Caixa Econômica Federal'],
            ['code' => '105', 'name' => 'Lecca Cfi S.A'],
            ['code' => '107', 'name' => 'Banco BOCOM BBM S.A.'],
            ['code' => '108', 'name' => 'Portocred S.A'],
            ['code' => '114', 'name' => 'Central Cooperativa De Crédito No Estado Do Espírito Santo'],
            ['code' => '117', 'name' => 'Advanced Cc Ltda'],
            ['code' => '121', 'name' => 'Banco Agibank S.A.'],
            ['code' => '136', 'name' => 'UNICRED COOPERATIVA'],
            ['code' => '143', 'name' => 'Treviso Cc S.A'],
            ['code' => '159', 'name' => 'Casa Credito S.A'],
            ['code' => '172', 'name' => 'Albatross Ccv S.A'],
            ['code' => '180', 'name' => 'Cm Capital Markets Cctvm Ltda'],
            ['code' => '184', 'name' => 'Banco Itaú BBA S.A.'],
            ['code' => '188', 'name' => 'Ativa Investimentos S.A'],
            ['code' => '189', 'name' => 'Hs Financeira'],
            ['code' => '190', 'name' => 'Servicoop'],
            ['code' => '191', 'name' => 'Nova Futura Ctvm Ltda'],
            ['code' => '196', 'name' => 'Banco Fair Corretora de Câmbio S.A'],
            ['code' => '197', 'name' => 'Stone Pagamentos'],
            ['code' => '204', 'name' => 'Banco Bradesco Cartões S.A.'],
            ['code' => '208', 'name' => 'Banco BTG Pactual S.A.'],
            ['code' => '212', 'name' => 'Banco Original'],
            ['code' => '213', 'name' => 'Banco Arbi S.A.'],
            ['code' => '217', 'name' => 'Banco John Deere S.A.'],
            ['code' => '218', 'name' => 'Banco BS2 S.A.'],
            ['code' => '222', 'name' => 'Banco Credit Agricole Brasil S.A.'],
            ['code' => '224', 'name' => 'Banco Fibra S.A.'],
            ['code' => '233', 'name' => 'Banco Cifra S.A.'],
            ['code' => '237', 'name' => 'Banco Bradesco S.A.'],
            ['code' => '241', 'name' => 'Banco Clássico S.A.'],
            ['code' => '243', 'name' => 'Banco Máxima S.A.'],
            ['code' => '246', 'name' => 'Banco ABC Brasil S.A.'],
            ['code' => '260', 'name' => 'Nubank'],
            ['code' => '265', 'name' => 'Banco Fator S.A.'],
            ['code' => '266', 'name' => 'Banco Cédula S.A.'],
            ['code' => '280', 'name' => 'Banco Willbank'],
            ['code' => '286', 'name' => 'Ccr De Ouro'],
            ['code' => '290', 'name' => 'PagBank'],
            ['code' => '300', 'name' => 'Banco de La Nacion Argentina'],
            ['code' => '318', 'name' => 'Banco BMG S.A.'],
            ['code' => '320', 'name' => 'Banco Ccb Brasil S.A'],
            ['code' => '323', 'name' => 'Mercado Pago'],
            ['code' => '335', 'name' => 'Banco Digio S.A'],
            ['code' => '336', 'name' => 'Banco C6 S.A – C6 Bank'],
            ['code' => '340', 'name' => 'Superdigital'],
            ['code' => '341', 'name' => 'Banco Itaú'],
            ['code' => '348', 'name' => 'Banco Xp S/A'],
            ['code' => '368', 'name' => 'Banco Carrefour'],
            ['code' => '370', 'name' => 'Banco Mizuho do Brasil S.A.'],
            ['code' => '376', 'name' => 'Banco J. P. Morgan S.A.'],
            ['code' => '380', 'name' => 'PicPay'],
            ['code' => '389', 'name' => 'Banco Mercantil do Brasil S.A.'],
            ['code' => '394', 'name' => 'Banco Bradesco Financiamentos S.A.'],
            ['code' => '412', 'name' => 'Banco Capital S.A.'],
            ['code' => '422', 'name' => 'Banco Safra'],
            ['code' => '456', 'name' => 'Banco MUFG Brasil S.A.'],
            ['code' => '461', 'name' => 'Asaas'],
            ['code' => '473', 'name' => 'Banco Caixa Geral – Brasil S.A.'],
            ['code' => '479', 'name' => 'Banco ItauBank S.A.'],
            ['code' => '494', 'name' => 'Banco de La Republica Oriental del Uruguay'],
            ['code' => '495', 'name' => 'Banco de La Provincia de Buenos Aires'],
            ['code' => '505', 'name' => 'Banco Credit Suisse (Brasil) S.A.'],
            ['code' => '600', 'name' => 'Banco Luso Brasileiro S.A.'],
            ['code' => '604', 'name' => 'Banco Industrial do Brasil S.A.'],
            ['code' => '612', 'name' => 'Banco Guanabara S.A.'],
            ['code' => '626', 'name' => 'Banco Ficsa S.A.'],
            ['code' => '637', 'name' => 'Banco SOFISA S.A (SOFISA DIRETO)'],
            ['code' => '653', 'name' => 'Banco Indusval S.A.'],
            ['code' => '654', 'name' => 'Banco A.J.Renner S.A.'],
            ['code' => '655', 'name' => 'Banco VOTORANTIM S.A'],
            ['code' => '707', 'name' => 'Banco Daycoval S.A.'],
            ['code' => '720', 'name' => 'Banco Maxinvest S.A.'],
            ['code' => '735', 'name' => 'Neon Pagamentos'],
            ['code' => '739', 'name' => 'Banco Cetelem S.A.'],
            ['code' => '741', 'name' => 'BANCO RIBEIRÃO PRETO'],
            ['code' => '743', 'name' => 'Banco Semear S.A'],
            ['code' => '745', 'name' => 'Banco Citibank S.A.'],
            ['code' => '746', 'name' => 'Banco Modal S.A.'],
            ['code' => '747', 'name' => 'Banco Rabobank Internacional Do Brasil S.A'],
            ['code' => '748', 'name' => 'Banco Cooperativo Sicredi S.A.'],
            ['code' => '752', 'name' => 'Banco BNP Paribas Brasil S.A.'],
            ['code' => '756', 'name' => 'Banco Cooperativo do Brasil S.A. – BANCOOB'],
            ['code' => '757', 'name' => 'Banco KEB HANA do Brasil S.A.']
        ],['code'],['name']);
    }
}
