/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColorField: typeof import('./components/inputs/ColorField.vue')['default']
    DateField: typeof import('./components/inputs/DateField.vue')['default']
    DetailsPage: typeof import('./components/DetailsPage.vue')['default']
    PasswordField: typeof import('./components/inputs/PasswordField.vue')['default']
    TablePage: typeof import('./components/TablePage.vue')['default']
    TimeField: typeof import('./components/inputs/TimeField.vue')['default']
  }
}
